In [1]:
import numpy as np
import torch

In [2]:
x = torch.rand(5,3)
y = torch.rand(5,3)

In [3]:
x

tensor([[0.0866, 0.5392, 0.7406],
        [0.0709, 0.9392, 0.0202],
        [0.3623, 0.0967, 0.1284],
        [0.8878, 0.2397, 0.9057],
        [0.5041, 0.2177, 0.4594]])

In [4]:
y

tensor([[0.5146, 0.3953, 0.9384],
        [0.8688, 0.7290, 0.2678],
        [0.6548, 0.6163, 0.9700],
        [0.3353, 0.7127, 0.9080],
        [0.9780, 0.2299, 0.9426]])

In [5]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[0.6012, 0.9345, 1.6789],
        [0.9397, 1.6681, 0.2879],
        [1.0171, 0.7129, 1.0984],
        [1.2232, 0.9524, 1.8138],
        [1.4821, 0.4476, 1.4019]])


In [6]:
print(y[:, 2])

tensor([0.9384, 0.2678, 0.9700, 0.9080, 0.9426])


In [10]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2128])
-0.21275313198566437


In [13]:
a = torch.ones(3)
b = a.numpy()
a.add_(3)
print(a)

tensor([4., 4., 4.])


In [14]:
print(b)

[4. 4. 4.]


In [15]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [16]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [17]:
a = torch.arange(1,4,1, dtype=torch.float)
a

tensor([1., 2., 3.])

In [18]:
a.mean()

tensor(2.)

In [19]:
a.sum()

tensor(6.)

In [20]:
a.max()

tensor(3.)

In [21]:
a.min()

tensor(1.)

In [22]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

print(torch.add(a,b).sum())

tensor(21.)


In [24]:
import math
a = torch.tensor([math.radians(30), math.radians(60), math.radians(90)])
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [25]:
a = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float)
b = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.float)

print(torch.mm(a,b))

tensor([[22., 28.],
        [49., 64.]])


In [26]:
a @ b

tensor([[22., 28.],
        [49., 64.]])